### ISSUE TITLE
Why GAE

### ISSUE THREAD

**Issue by frewsxcv** [MayOneUS/pledgeservice#1]
Why not just stick with a framework like [Flask](http://flask.pocoo.org/) so we're not limited to GAE?

**Comment by hjfreyer** [comment]
I'm not sure what you mean by "limited to GAE". GAE python uses WSGI handlers just like any other app server. Flask produces wsgi servlets, so we can use that if desired. 

Either way, I expect the server-side functionality to be pretty minimal.

**Comment by frewsxcv** [comment]
Fair enough
