### ISSUE TITLE
remove link to create pledge page from thank you page 

### ISSUE THREAD

**Issue by piebob** [MayOneUS/pledgeservice#104]
https://pledge.mayday.us/receipt/  needs to not direct people to create a pledge page now that we've reached the goal. 
  pledgeservice / backend / email / thank-you.txt

**Comment by jtolio** [comment]
how come? we're going to need orders of magnitude more for 2016. why stop? i mean, you're probably right, just curious

**Comment by piebob** [comment]
main reason is that we aren't doing 'pledges' any more. if we want to keep the personal fundraising pages, that would be fine by me, we just need to make it clear that they're donations from now on. we should raise it in Monday's call.

**Comment by jwhite66** [comment]
Done!
