### ISSUE TITLE
Emails sometimes don't get added to mailchimp

### ISSUE THREAD

**Issue by jwhite66** [MayOneUS/pledgeservice#105]
Aaron reports:
There is a persistent issue when sending email users across to mail chimp.

Sometimes errors happen and people do not get added. You can see tons of these if you filter the logs for errors only.

Also, because the mail chimp send is deferred, the task queur keeps retrying these, filling up both task queue and error logs.

**Comment by brad** [comment]
I think the appropriate action here is to catch any Exception while trying to subscribe the user. We can still log the error, and comb the logs to try and manually add users if desired. What do you think @jwhite66 ?

**Comment by erinzm** [comment]
Or retry on the exception, or put it in a special queue.

**Comment by jwhite66** [comment]
That sounds wise, but I want a chance to dive into the logs and see if I can suss out what is happening.  It's very puzzling, because almost all emails go through.

**Comment by erinzm** [comment]
Aren't you already putting all that stuff in the logs?

**Comment by jwhite66** [comment]
The logs seem to suggest that a lot of the errors are malformed emails, or emails from subscribers that have perma-opted out of mailchimp.  There are a few other cases; I'm going to see if I can understand those.  Most confusing is that there is _always_ an error log for making a mailchimp connection, which I cannot find reflected in their code(their code has an info log, which I see, but then we also always get an error log after it.  Strange).

**Comment by jwhite66** [comment]
Looking deeper, the one case I found was a user who had put a non breaking space in their email; it shouldn't have gone through.  I even found a case where an email didn't go through due to timeout, and was retried and sent later.

I think this is working correctly, with the sole exception of why the heck the extra error log is put in there when the connection start.

**Comment by brad** [comment]
@ArchimedesPi Deferred tasks always retry on exception, at least the documentation says so. That's why I suggested catching the exception. If there are any malformed emails then they will stay in the queue forever, retrying and failing over and over again.

**Comment by erinzm** [comment]
Can we put a regexp on the email address field to validate it?

**Comment by jwhite66** [comment]
Possibly; we could potentially even live query mailchimp when they give us our email.  Mind doing me a favor, though, and adding that as a different issue?  I'm fairly confident that this issue can be closed as working.

**Comment by erinzm** [comment]
Email validation issue:
https://github.com/MayOneUS/pledgeservice/issues/107
