### ISSUE TITLE
Validate emails for mailchimp

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/pledgeservice#107]
We should use a regexp to validate all email addresses _before_ they go to Mailchimp.

**Comment by brad** [comment]
Let's make sure to use a library for this. http://blog.newrelic.com/2014/07/08/7-things-never-code/

**Comment by erinzm** [comment]
Yeah, after reading that, I _totally_ agree ;).
BTW thanks for that article @brad!

**Comment by brad** [comment]
:smile: no problem, I came across that on Twitter this morning and just had
to share.

**Comment by erinzm** [comment]
@brad [this](https://github.com/SyrusAkbary/validate_email) looks like it'll work, any objections? It checks against RFC2822 by default, it can also check that email server and account are valid.

**Comment by erinzm** [comment]
Actually [mailgun/flanker](https://github.com/mailgun/flanker) looks better, let's use that!

**Comment by brad** [comment]
:anguished: Looking over the code a bit, it turns out we are actually using a validation library already (validictory) but it doesn't have an email validator! There was a [pull request](https://github.com/sunlightlabs/validictory/pull/51) for one, but it was rejected :disappointed:

**Comment by brad** [comment]
I'm really surprised mailchimp doesn't have a validator built-in to their API.

**Comment by Rio517** [comment]
We're no longer using mailchip. Marking as closed.
