### ISSUE TITLE
Email templating

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/pledgeservice#109]
How are we templating the emails in `backend/email`?

**Comment by brad** [comment]
Those are just using python string formatting. Probably wouldn't be too much work to put them through Jinja2 instead.

**Comment by erinzm** [comment]
OK, if you want I can convert them to Jinja - Jinja and Flask are my area
of (Python) expertise.

**Comment by brad** [comment]
Sure, I certainly don't have anything against that.

**Comment by erinzm** [comment]
master/backend/handlers.py lines 206, 207, and 222 look like the lines to replace with Jinja stuff.

**Comment by erinzm** [comment]
No longer matters given current mayone state.
