### ISSUE TITLE
Email field removes '+'

### ISSUE THREAD

**Issue by frewsxcv** [MayOneUS/pledgeservice#135]
`https://mayday.us/campaigns/what-we-learned-in-2014/?email=coreyf+mayday@rwell.org`

![screen shot 2014-12-09 at 4 00 36 pm](https://cloud.githubusercontent.com/assets/416575/5365760/862689a2-7fbc-11e4-8d8b-5f2d9995b1ff.png)

**Comment by Rio517** [comment]
Fixed! Thanks for bringing to our attention!
