### ISSUE TITLE
Issue with SSL reported through Email

### ISSUE THREAD

**Issue by aaronlifshin** [MayOneUS/pledgeservice#14]
On Sun, May 4, 2014 at 11:09 PM, Stephen Demjanenko sdemjanenko@gmail.com wrote:
Chrome Version 34.0.1847.131

When I open the https icon I see:

The identity of this website has not been verified.
 • Server's certificate is not trusted.
 • Server's certificate cannot be checked.

Its complaining that the certification was signed by an unknown authority (Geotrust).

Firefox doesn't seem to have this issue.

Subject:    Re: Chrome detects pledge form as insecure
Date:   Sun, 4 May 2014 23:13:40 -0700
From:   Stephen Demjanenko sdemjanenko@gmail.com
To: Webmaster webmaster@mayone.us

I do have cert revocation checking turned on (which is not the default behavior in Chrome).

![issueimage2](https://cloud.githubusercontent.com/assets/3149504/2875812/4a36e158-d427-11e3-9601-4c426157f651.png)
![issueimage1](https://cloud.githubusercontent.com/assets/3149504/2875813/544b622c-d427-11e3-8018-a85097d1e090.png)

**Comment by hjfreyer** [comment]
I think I've figured it out. I think it's due to certificate chain issues http://stackoverflow.com/questions/13862908/ssl-certificate-is-not-trusted-on-mobile-only

Working on digging a bit more into a fix.

**Comment by hjfreyer** [comment]
Huh. Clearing my cache seemed to fix it... Not sure how to debug it now :P

**Comment by hjfreyer** [comment]
Reopening for tracking.

**Comment by brad** [comment]
Ahh yes, I've been here before. To resolve the issue I had to add the intermediate certificates on the server. Is there a way to do that on GAE?

**Comment by brad** [comment]
Ah ha, looks like you need to append the intermediate certificates to the end of the public certificate: https://developers.google.com/appengine/docs/ssl#certificate_requirements

**Comment by hjfreyer** [comment]
Yeah I figured it was something like that. Lemme give it a try. Are you on hangouts? Can you reproduce the issue locally?

**Comment by hjfreyer** [comment]
Status:
- The intermediate cert was missing from the bundle. Many validators were complaining, including GeoTrust's
- I added one of the intermediate certs GeoTrust links to. Now the validators are happier, but geotrust still gives a warning about "older browsers"
- Difficult to determine whether it's working or not. Brad's still seeing the issue but it might be a cache thing.

**Comment by jtolio** [comment]
we spend a ton of time dealing with ssl certificates at my work. i'll see if me or one of my coworkers can take a look this morning when i get in

**Comment by hjfreyer** [comment]
Pushed another certificate and all the validators are happy. I'm thinking this is fixed. @aaronlifshin can you reach out to the original user?

**Comment by aaronlifshin** [comment]
Will do.

A

**Comment by aaronlifshin** [comment]
User has confirmed issue is resolved.
