### ISSUE TITLE
Enable push-to-deploy and Google Cloud-based build system

### ISSUE THREAD

**Issue by hjfreyer** [MayOneUS/pledgeservice#15]
Deploying should be a single command, and users should not have to worry about whether they're using the test or prod Stripe keys - it should just work.

**Comment by brad** [comment]
:+1:

**Comment by hjfreyer** [comment]
Push to deploy doesn't seem to quite fit the bill for our set up - it's mostly targeted at Java. That said, the release procedure is much more streamlined, and documented in the README, so I'm calling this done.
