### ISSUE TITLE
Decide fate of WordPress instance

### ISSUE THREAD

**Issue by hjfreyer** [MayOneUS/pledgeservice#17]
With WP only serving static content, it doesn't need to be on a dedicated box anymore. Also, the main page is currently an HTML file, which is not super editable. Maybe we can find a cloud provider that gives us easy editing without all the config WP needs? Or maybe we can just return WP to shared hosting, and stick it behind Cloudflare? This is a medium term concern, and shouldn't be worried about until all the data is out of WP and transferred into GAE.

**Comment by aaronlifshin** [comment]
oops

**Comment by frewsxcv** [comment]
@aaronlifshin Stop being so rude

(for clarification, this is sarcasm)

**Comment by aaronlifshin** [comment]
Let's give it some time.  I have a feeling the server will come in handy for other campaigns, I would not return to shared hosting.

**Comment by aaronlifshin** [comment]
@frewsxcv Please tell me you're joking

**Comment by frewsxcv** [comment]
Sorry, forgot to wrap it in `<sarcasm>` tags.

Do we expect that this repository will eventually host the main site after the pledging is over?

**Comment by hjfreyer** [comment]
Yeah I don't think we should rush into anything. But remember that cost analysis I did? I'd like to amend my projections. At this point the cost of running on app engine for the month is looking like it'll be closer to... $0.

**Comment by hjfreyer** [comment]
Oh, actually, I think SSL costs $5 a month. So $5.

**Comment by jtolio** [comment]
lol awesome

**Comment by frewsxcv** [comment]
Well, why wouldn't we shut down the MT server and completely migrate to GAE?

**Comment by hjfreyer** [comment]
@frewsxcv The main concern is ease of content editing for the "messaging" parts of the site, so lessig and Brian don't have to worry about breaking anything if they want to change copy, and don't have to redeploy.

**Comment by aaronlifshin** [comment]
We want to maintain the ability for non-programmer admins to edit the
messages on the site.

**Comment by hjfreyer** [comment]
But there may be cheaper ways to accomplish that, is all I'm saying. Not a huge deal either way.

**Comment by frewsxcv** [comment]
What options do we have then? Abstract out the content data into a format like markdown so they can easily edit them? Switch to a different CMS platform?

**Comment by brad** [comment]
If #15 was done and the content was stored in markdown files, that might be feasible using Github's built-in editor. It does give you the ability to preview.

**Comment by aroben** [comment]
> Maybe we can find a cloud provider that gives us easy editing without all the config WP needs?

A [Jekyll](http://jekyllrb.com)-based site on [GitHub Pages](https://pages.github.com) might be a good option. When combined with [prose.io](http://prose.io/#about) it's really easy to edit/preview/deploy changes right in the browser (or of course you can use GitHub's built-in editor). This is how the US [Open Data Policy](http://project-open-data.github.io) is built/hosted. (The Open Data Policy uses a *.github.io domain, but [custom domains are supported](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages) too.)

Pros:
- Free
- Uses Fastly as a CDN so should be able to handle lots of traffic [very quickly](http://www.jeremymorgan.com/blog/programming/how-fast-are-github-pages/)
- Easy editing of Markdown content
- Automatic build/deploy on push
- No extra accounts to manage (just uses GitHub auth)

Cons:
- Adds Ruby/Jekyll to our dependencies (though these don't run on the server; they're just used for building the static site on each push)

**Comment by aroben** [comment]
_Disclaimer: I work for GitHub so I may be biased :grin:_

**Comment by aaronlifshin** [comment]
There doesn't seem to be a compelling need to migrate off of wordpress at the moment.

**Comment by frewsxcv** [comment]
Agreed about not migrating off for now. For at least the pledge drive, I think our current setup should suffice since our content isn't changing that much. Though afterwards, I think a workflow like the one @aroben mentioned would be the way to go.

**Comment by BrettRToomey** [comment]
Yes, I completely agree with waiting and, eventually, migrating to the aforementioned system.

**Comment by brad** [comment]
:+1: If we finish all the high priority items and have a massive surplus of
programmer hours available, we should look into it then.

---

Brad Pitcher

**Comment by aaronlifshin** [comment]
Closing for now.  WP gets to stay, because it's working fine.

**Comment by hjfreyer** [comment]
I think the static "index.html" situation needs to get resolved, which I was considering to be in the scope of this bug. Even if we stick with WP on dedicated hosting, the front page should be editable via WYSIWYG, and the database/plugin set should be cleaned out so we don't have lingering user data / performance issues waiting to happen. I'm happy to open up a new bug for those things if you think that doesn't really jive with this one.

**Comment by aaronlifshin** [comment]
OK. Makes sense.

The first step would be to get the new progress counter that reads from GAE
into the PHP.

Then we could just test and see how much slower it is.

Maybe trog could take this task?

A

**Comment by hjfreyer** [comment]
I imagine if the WP has no dynamic content and SuperCache (or w/e) turned
on, it'd be nearly the same as the static page, but trog would know better.

**Comment by trogau** [comment]
Sure, I can take a crack at this now. 
@hjfreyer : the box is so overspec'ed I think it'll run fine even w/o explicit caching, but it's easy enough to turn on once the home page is fixed up.

**Comment by trogau** [comment]
I've gotten the new pledge progress bar working & integrated a few of the other changes that I found in the CSS. Some of the content is out-of-date but I believe Brian is working on that now. 

Hilariously the hardest part was just figuring out how to make WordPress respond via /index.php instead of automatically redirecting to /index.html. If you would like to preview the WP version, your IP address needs to be added to the end of wp-config.php (look for "disable canonical redirect").

**Comment by nickbender** [comment]
I completely understand that the migration isn't a priority for the present. However, the volunteer list shows quite a few rubyists that could add a lot to the project as it moves forward post Jekyll migration. 

Several devs (including @aroben and I) could fork the project and begin the migration at any point. Beginning this transition soon would only ease the platform switch when it does become a necessity.

Having used github pages before, it is by far the easiest to deploy and requires almost zero config. It's expandable and easy to abstract as well, to make contributions less brittle.

**Comment by hjfreyer** [comment]
If you hack together a prototype that looks roughly like the current page
(take a look at the jade files which are currently unused in this project
as a starting point), we can totally run the workflow by L+B and see what
they think. I've become even warier of the WP instance since we discovered
that somehow people were still making pledges through the old interface.

**Comment by aaronlifshin** [comment]
I feel like this is taking on work that doesn't need to be done, just
because we have the resources to do it.

We could use your help on the New Hampshire Rebellion site instead.

http://www.nhrebellion.org/

Can you make a Ruby Clone of that instead, which pushes people into
Nationbuilder?

The site information architecture will need to be redesigned, but it will
be much easier to do that if it's a Ruby site.

I will get you access to the Nationbuilder sandbox site to play with.

A

**Comment by hjfreyer** [comment]
I think the WP outage last night elevates the priority on moving mayone.us to something more static and foolproof. @aaronlifshin what are your thoughts?

**Comment by aaronlifshin** [comment]
The outrage made us look really bad. Cms continues to be a key business
requirement that we cannot drop.

**Comment by jtolio** [comment]
I'd be interested in seeing options for GAE-hosted CMS tools. 

There have been a few people on Facebook who have started their own personalized MayOne pages. It might be nice if we found a CMS that was something of a wiki with ACLs for certain pages?

https://www.facebook.com/groups/282646648577039/permalink/283333185175052/

**Comment by aroben** [comment]
Seems like GitHub Pages has been decided upon? https://github.com/MayOneUS/mayoneus.github.io

**Comment by aaronlifshin** [comment]
Yep.  The question now is how to get them and the pledge site to use the
same "theme" code.

A

**Comment by erinzm** [comment]
We should create a new `style` repo; fill it up with SASS, and recursively pull it into both the pledge site and the github pages site. It _should_ work; Jekyll can parse SASS _I think_. Then Github pages handles the builds of the static site; we could use a Continuous Deployment service to build and push tagged commits to GAE.

**Comment by aaronlifshin** [comment]
The fate of the wordpress instance has been decided.
