### ISSUE TITLE
email existing users link to pledge management page

### ISSUE THREAD

**Issue by jtolio** [MayOneUS/pledgeservice#20]
once #19 and #8 are done, we need to tell everyone. 

this is going to require copy from lessig, and really strong language telling people we need all fields filled in

**Comment by kerryboyko** [comment]
I'm working on the wording and will get @lessig's approval first.

**Comment by erinzm** [comment]
Isn't this _done_ in pledgepages?

**Comment by aaronlifshin** [comment]
yes we emailed people links to manage their pledge pages in the past

**Comment by erinzm** [comment]
[Just so you know @aaronlifshin, I'm trying to clean up our issue queue to
get to the stuff that really matters]

**Comment by aaronlifshin** [comment]
I like that you do this!

When I get feature requests that are urgent, you think I should add them
here?

A

**Comment by erinzm** [comment]
Yeah, you should @aaronlifshin. Having issues and **especially using tags** helps devs get to stuff sooner. A fontend dev can see stuff tagged `frontend` &c.

**Comment by aaronlifshin** [comment]
I'll try to get better about this.

A
