### ISSUE TITLE
Unit test suite

### ISSUE THREAD

**Issue by brad** [MayOneUS/pledgeservice#21]
A unit test suite will remove the fear in making changes and give us extra confidence.

**Comment by stin7** [comment]
I've started adding a framework to a new branch on my fork: https://github.com/stin7/mayone-app-engine/tree/add-unittest-framework 

when I feel it's more complete I'll submit a pull request. in the mean time - any advice or thoughts on my implementation are appreciated!

**Comment by brad** [comment]
That looks like an excellent start! I just have one request: I'd like a way to override the SDK_PATH when I run the tests, because the path that is hard coded is not the same on my machine. Thanks for working on this!

**Comment by stin7** [comment]
Cool - added a prompt to override default SDK_PATH

**Comment by stin7** [comment]
Just submitted a pull request with the new testing framework - let me know if you have any questions or something isn't working.

Cheers,
Austin
