### ISSUE TITLE
make a graph of amount pledged over time

### ISSUE THREAD

**Issue by jtolio** [MayOneUS/pledgeservice#22]
a time series density graph would be awesome

**Comment by hjfreyer** [comment]
Was planning on doing this. Also a histogram of pledge amounts. Up to lessig whether these should be public or not.

**Comment by kerryboyko** [comment]
You know, I'm not bad with data, so let me know if I can help out on this one.

**Comment by erinzm** [comment]
Not sure what legal status is on this right now, also I don't think we really care about this anymore? It's not about _personal_ pledges, we've got the map instead.

**Comment by jwhite66** [comment]
I agree that we should close this issue, and open new issues for any ways in which our current visualization is not good enough.
