### ISSUE TITLE
Run a pre-auth charge for newly created customers

### ISSUE THREAD

**Issue by brad** [MayOneUS/pledgeservice#23]
https://stripe.com/docs/api#create_charge

Make sure `capture=False`

**Comment by aaronlifshin** [comment]
We have to be careful here.  What if we change something, and cannot collect at all after the auth expires?  Because we are likely to collect after more than 7 days elapse.

**Comment by brad** [comment]
Yes, we need to be very careful here. From what I understand, that first charge will expire, and we will just need to create a new charge.

**Comment by aaronlifshin** [comment]
Will there also need to be additional error handling coded if the auth
fails?

**Comment by brad** [comment]
Maybe, but I think stripe handles that for us. We can locally try out [fake test cards](https://stripe.com/docs/testing) to see what happens

**Comment by hjfreyer** [comment]
I think this is a policy decision that should be escalated to Brian or Lessig. Have either of them commented?

If it were up to me, I'd carry on without preauthorization. It _decreases_ the chance that credit cards will be rejected, but doesn't really eliminate it in any way, and it adds some complexity to the system.

**Comment by brad** [comment]
Good point. I was getting ahead of myself. They have not yet weighed in on the subject.

**Comment by jwhite66** [comment]
This issue is now moot.  Closing.
