### ISSUE TITLE
Visual artifact on the Stripe modal

### ISSUE THREAD

**Issue by brad** [MayOneUS/pledgeservice#24]
For some reason the stripe modal has a small white box layed over the top of the fields. It is an iframe, but surely there is some way to make it go away.

![screenshot from 2014-05-05 20 46 22](https://cloud.githubusercontent.com/assets/1614/2885845/898aecd2-d4d1-11e3-8a2b-8ca5ca9af522.png)

**Comment by aroben** [comment]
I don't see this in Safari 7.0.3, Chrome 34.0.1847.131, Firefox 27.0.1, or Firefox 29.0 on OS X 10.9.2. What browser/OS are you seeing it on?

**Comment by aroben** [comment]
Here's Safari, for example:

![screen shot 2014-05-06 at 8 45 35 am](https://cloud.githubusercontent.com/assets/917945/2889481/d33f486e-d51c-11e3-8b75-8da9d8f8fcff.png)

**Comment by brad** [comment]
It's there. See how the line between country and zip doesn't continue all
the way to the left?

**Comment by aroben** [comment]
That looks intentional to me. The only full-width line is between "Name" and "Address". Fields within "Address" are separated by non-full-width lines.

**Comment by aroben** [comment]
…where by "Address" I mean "the address-related fields".

**Comment by brad** [comment]
I guess your right, stripe has a picture that looks just like yours on https://stripe.com/checkout.

So the real problem is that the country field is not white.
Firefox 28 and Chromium Version 34.0.1847.132 (265804) on Linux
It's probably a Linux thing. I'll file a bug with stripe.

**Comment by brad** [comment]
Hmm, I'm not sure if that piece of stripe is open source. Does anyone know where I could file this with stripe?

**Comment by aroben** [comment]
I'd try https://support.stripe.com/email

**Comment by brad** [comment]
I ended up tweeting @StripeSupport, I usually get better results using twitter.

**Comment by brad** [comment]
FWIW, I can make it look exactly like yours if I open the debugger tools and add `background-color: white;` to the country dropdown css.

**Comment by hjfreyer** [comment]
Yeah, but it's in an iframe out of our control.

**Comment by brad** [comment]
I pointed the stripe support twitter account to this issue, I'm hoping they
will come and see it ;-)

---

Brad Pitcher

**Comment by brad** [comment]
@hjfreyer It's not totally out of our control. If we really wanted to we could hack some javascript to fix it, but I don't feel good about that.

**Comment by michaelvillar** [comment]
Hey, I work on Stripe Checkout :)

It's definitely a bug and probably happens only on Linux. I'm filling an issue internally :)

Thanks!

**Comment by brad** [comment]
Thank you @michaelvillar :beers:

**Comment by hjfreyer** [comment]
@michaelvillar Seeing it on OS X Chrome as well.

**Comment by michaelvillar** [comment]
Wow, that's weird though. I'm on OS X Chrome 24 and I don't see that at all. What exactly do you see?

**Comment by hjfreyer** [comment]
Not at home at the moment - when I get there I'll send my version number
and screenshot.

**Comment by hjfreyer** [comment]
Version 35.0.1916.86 beta
![screen shot 2014-05-07 at 1 19 09 pm 1](https://cloud.githubusercontent.com/assets/271308/2906013/c5355aca-d60b-11e3-961c-210ede405703.png)

**Comment by jamesreggio** [comment]
Ah, that's the beta for the next major release of Chrome.

Perplexingly, they've decided to change the user-agent stylesheet to set a background of `rgb(248, 248, 248)` for `select` elements. (Here's a [screenshot](https://twitter.com/jamesreggio/status/466681757429809152) of the Web Inspector.)

I also work at Stripe with @michaelvillar. We'll get a fix shipped shortly. Thanks for bringing this to our attention.

**Comment by brad** [comment]
Thanks @jamesreggio I'm also seeing the problem in Firefox 28 and Chromium Version 34.0.1847.132 (265804) on Linux. Hopefully the fix works there too :smile:

**Comment by erinzm** [comment]
This still happens. Even with `newpledge`.

**Comment by aaronlifshin** [comment]
Didn't stripe admit this was their issue?

**Comment by erinzm** [comment]
Yeah, but I thought they'd fix it soon(ish), seeing as they probably have a
fair number of Linux users.

**Comment by jamesreggio** [comment]
Ah, apologies for the recurrence of this bug. We fixed it for Chrome back in mid-May, but the solution for Firefox on Linux is more involved. (It has to do with the trickiness of hiding the built-in dropdown arrow for `select` elements in Firefox.)

I'll see what I can do, and will be sure to keep you updated.

**Comment by jamesreggio** [comment]
Just to let you know, we deployed an update today that should 'fix' this issue, as much as is possible. The country field in Checkout should look roughly like this in Firefox on Linux:

![country-tweak](https://cloud.githubusercontent.com/assets/822205/3650899/ee4f7d82-1120-11e4-8581-2e473e0aaadb.png)

(The soft edges/artifacting on the right side is the result of a bad screen-share session.)

Firefox makes it very difficult to style select elements, so this is the best we can do.

**Comment by jwhite66** [comment]
Very cool; thanks for the follow up!

**Comment by erinzm** [comment]
Yay!
Looks way better than it did before :)
