### ISSUE TITLE
Emails are not being added to stripe

### ISSUE THREAD

**Issue by aaronlifshin** [MayOneUS/pledgeservice#25]
Wordpress used to put email into the customer->email and customer->description fields.  But this is not working any more from AppEngine.

Makes it more difficult to collect exports.

**Comment by aroben** [comment]
It looks like we try to get the email address [from the Stripe token via `token.email`](https://github.com/MayOneUS/app-engine/blob/8e1f5bf84e8293b9a90f224352878d51f1b8a456/markup/pledge.jade#L31-L33), but according to the [token API docs](https://stripe.com/docs/api#token_object) there is no such property.

**Comment by hjfreyer** [comment]
Interesting. That value is, in fact, being set. But if it's not documented
we should avoid it. I'll look into this.

**Comment by aroben** [comment]
Are the emails ending up in the Pledge model? We pass them to Pledge at the [same place](https://github.com/MayOneUS/app-engine/blob/8e1f5bf84e8293b9a90f224352878d51f1b8a456/backend/main.py#L128-L138) we pass them to Stripe.

**Comment by jtolio** [comment]
whoops, sorry guys, i forgot to mention this commit happened since this ticket was filed. https://github.com/MayOneUS/app-engine/commit/8e1f5bf84e8293b9a90f224352878d51f1b8a456

**Comment by jtolio** [comment]
hmm, on further thought, i don't like 8e1f5bf, cause it's violating single-source-of-truth for mutable data. i'll get rid of the metadata section

**Comment by jtolio** [comment]
https://github.com/MayOneUS/app-engine/commit/6283a10c195d3378e935abba743d49db3daf91c3

**Comment by aroben** [comment]
So looks like we now send customer emails to Stripe but all other metadata to the Pledge model. Does that mean this is fixed (and can be closed)?

**Comment by aaronlifshin** [comment]
That commit is not yet tested or deployed

**Comment by aaronlifshin** [comment]
Fixed now.
