### ISSUE TITLE
"Total" queries are getting expensive

### ISSUE THREAD

**Issue by hjfreyer** [MayOneUS/pledgeservice#27]
Some are taking as much as 30 seconds. The total is cached for 5 minutes per instance, so it's a small fraction of users that aren't seeing the progress bar for that long, but it's only going to get worse. 

The correct idea is to use a sharded counter pattern. It's simple to code up and I'll get on it when I get home.

**Comment by aroben** [comment]
I wonder how much mileage we'd get out of switching to a [projection query](https://developers.google.com/appengine/docs/python/datastore/projectionqueries) to avoid pulling all the customers' names, emails, etc. into memory, and making sure we have the right [indexes](https://developers.google.com/appengine/docs/python/datastore/indexes) in place. It would be a very small code change and probably a pretty good speedup.

**Comment by hjfreyer** [comment]
Ah, good call. I'll try that first. I'm used to BigTable at Google which doesn't really have features like that :)

**Comment by hjfreyer** [comment]
Fixed in 9ac0e7c
