### ISSUE TITLE
better slider

### ISSUE THREAD

**Issue by idiomatic** [MayOneUS/pledgeservice#43]
Visiting https://mayone.us/ causes Chrome or Firefox to use a lot of CPU.

Not observed with Safari, nor on any other page.

**Comment by erinzm** [comment]
By slider you mean...the total bar?

**Comment by idiomatic** [comment]
no, i mean the slideshow that automatically pans those depressing pictures across the screen.

to debug without the laptop melting, i need to set display:none on the correct element.  the CPU gets about 5x worse with the developer tools element inspector up.

**Comment by hjfreyer** [comment]
I don't like the slider as it is. The unused
http://pledge.mayone.ushomepage replaces it with a CSS transition fade
which I think is much less
distracting, and would probably be cheaper. Maybe we'll port that to the
new static page at some point.

On Wed, May 14, 2014 at 3:26 PM, brian harrison notifications@github.comwrote:

> no, i mean the slideshow that automatically pans those depressing pictures
> across the screen.
> 
> to debug without the laptop melting, i need to set display:none on the
> correct element. the CPU gets about 5x worse with the developer tools
> element inspector up.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MayOneUS/app-engine/issues/43#issuecomment-43125970
> .

## 

kthxbai,
Hunter

**Comment by aaronlifshin** [comment]
Yes, we want to change it to fade.

**Comment by erinzm** [comment]
@idiomatic This should be closed, the homepage redesign is working on this now.
