### ISSUE TITLE
Ruby problems

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/pledgeservice#46]
When Grunt runs the Sass task, it produces the following error on my system:

```
Running "sass:main" (sass) task
/usr/bin/env: ruby1.8: No such file or directory
Warning: Exited with error code 127 Use --force to continue.
```

**Comment by hjfreyer** [comment]
Do you have sass installed? Does it work when you run it standalone?

On Wed, May 14, 2014 at 6:25 PM, Liam M notifications@github.com wrote:

> When Grunt runs the Sass task, it produces the following error on my
> system:
> 
> Running "sass:main" (sass) task
> /usr/bin/env: ruby1.8: No such file or directory
> Warning: Exited with error code 127 Use --force to continue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MayOneUS/app-engine/issues/46
> .

## 

kthxbai,
Hunter

**Comment by erinzm** [comment]
It used to work globally until I ran `npm install` in this project's root.
It's probably completely specific to my setup. ;)
