### ISSUE TITLE
Update the embed tracker to be green and completed

### ISSUE THREAD

**Issue by aaronlifshin** [MayOneUS/pledgeservice#48]

**Comment by erinzm** [comment]
Ummm- As we're going to go for a larger goal now, I think it would be worthwhile to write some simple JS to check if we've hit the target, and then turn it green. Secondly, I thought the Github Pages system was _supposed_ to handle this?

**Comment by aaronlifshin** [comment]
It could be good to add that code to the tracker, I think.

The tracker is part of the pledge system, which is AppEngine.

A

**Comment by erinzm** [comment]
By "supposed", I meant that the color and completion status _should_ be
handled by Github Pages.
