### ISSUE TITLE
Why the extra pages under `markup`?

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/pledgeservice#50]
Why do we have all of the pages under `/markup` that are being served by Github Pages?

**Comment by jtolio** [comment]
we originally were planning on cutting straight over from wordpress cold turkey. we kept wordpress, and are moving to GHP, because we want to support easy non-technical-person editing.

the markup pages are just a relic from before we had that plan

**Comment by hjfreyer** [comment]
Yeah. Once we've migrated we should delete those. I like them being there
for now if we want to borrow from them.

**Comment by erinzm** [comment]
Got it. I suppose they'll be removed in a PR sometime soon.
