### ISSUE TITLE
Remove re-implemented static pages from pledgeservice

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/pledgeservice#59]
As of now (22 May '14), Github Pages is handling the homepage.
Why does the pledge service implement a homepage endpoint at `/`?
Actually, we _could_ put the pledge page at `/`, so that pledging goes on at `pledge.mayone.us`.

**Comment by hjfreyer** [comment]
Historical reasons. I haven't gotten rid of it yet, because it's useful to see the total when I'm debugging, but now that we have some tests it's likely not as big a deal (and I could always go to embed.html). But yes, those should go away eventually.

**Comment by erinzm** [comment]
Ah, I see.
