### ISSUE TITLE
Pledge thank you screen content text needs editing

### ISSUE THREAD

**Issue by LindaHartTolley** [MayOneUS/pledgeservice#73]
After submitting my June pledge, the thank you screen was auto-opened.  The last line content needs editing.  I added the parentheticated question marks to the quoted text below.

"Thank you for pledging $50.00 in support of Mayday. Here is how you can multiply your impact right now:

Make your own customized pledge page!
Share the Mayday experiment with your friends on (?) and (?)"

**Comment by aaronlifshin** [comment]
This is odd, others don't see it.

Is it possible you have a plug that blocks social sharing links?

A

**Comment by LindaHartTolley** [comment]
Thank you, Aaron.  I hope it might have been something of a transitory
glitch.  I used Chrome to send in my June pledge.  My husband donated via
Firefox and got the nice click through links to Facebook and Twitter.

Linda

Linda Hart Tolley
Administrative Officer / Curriculum and Assessment
Merritt Writing Program
University of California, Merced
lharttolley@ucmerced.edu

**Comment by aaronlifshin** [comment]
OK let's keep this open for a bit and see if we get other complaints.

**Comment by erinzm** [comment]
Stale. Probably an ad blocker, I don't think this is even relevant to the latest version of the site.
