### ISSUE TITLE
Twitter link on receipt page busted?

### ISSUE THREAD

**Issue by jwhite66** [MayOneUS/pledgeservice#75]
From Uservoice; ticket 3309:

I made my contribution but when I clicked the Twitter button afterwards, 
the message it generated did not properly format mayday.us as a url 
(missing http://). Please fix this.

**Comment by aaronlifshin** [comment]
I actually think this is by design?

**Comment by aaronlifshin** [comment]
Checking...

**Comment by aaronlifshin** [comment]
Checking on this, I think the PR team don't want it as a link for some
reason.  Weird.
