### ISSUE TITLE
Pledge page on foreign nationals is contradictory

### ISSUE THREAD

**Issue by jwhite66** [MayOneUS/pledgeservice#77]
A 'permanent resident alien' is, by definition  a foreign national.
(http://en.wikipedia.org/wiki/Foreign_national)
So you can't allow 'permanent resident aliens' and then, later, disallow them.
And, according to FEC rules:
  http://www.fec.gov/ans/answers_general.shtml#Can_nonUS_citizens_contribute
They are legal.
Given that, I'll submit a patch to remove 'foreign nationals'.

**Comment by aaronlifshin** [comment]
A 'permanent resident alien' is NOT a foreign national accroding to the def used by the FEC here: 

Can non-US citizens contribute?
Foreign nationals are prohibited from making any contributions or expenditures in connection with any election in the U.S. Please note, however, that "green card" holders (i.e., individuals lawfully admitted for permanent residence in the U.S.) are not considered foreign nationals and, as a result, may contribute. For additional information, consult our "Foreign Nationals" brochure.

**Comment by aaronlifshin** [comment]
Propose closing the issue

**Comment by jwhite66** [comment]
This is certainly not the biggest problem we're facing, but I'm pretty sure I'm right, and I'm pretty sure the guy who wrote in on this was right.  That is, the _conventional_ use of the term 'foreign national' means what Wikipedia says.  And, in fact, the department of Homeland Security uses it that way:  http://www.dhs.gov/profiles-legal-permanent-residents.  It's only the FEC that seems to have this special case definition of foreign national that excludes green card holders.  And either way you read it, there is no case where this change, presuming complete honesty on all parts, could allow someone in that is not allowed to contribute.  The first stanza covers all bases.  And, in fact, the foreign national bit doesn't really belong in the section it was in.

With all of that said, if this is copy that came from a non tech source, then changes should be reviewed by that non tech source, and it's priority is so small as to not really matter.

**Comment by aaronlifshin** [comment]
@brianboyko, can you please weigh in here?  You are the closest to legal on this issue.
Jwhite, I do believe that this is legal text provided by lawyers, so it's a process to get this to change.

**Comment by piebob** [comment]
hey, we can close this, per a change i made after getting approval from Lessig. it now says:
"I am not a foreign national (permanent resident aliens excepted), federal contractor, national bank, or corporation chartered by an act of Congres."
