### ISSUE TITLE
previous pledge(s) management page

### ISSUE THREAD

**Issue by jtolio** [MayOneUS/pledgeservice#8]
the url should be something like

pledge.mayone.us/pledges/&lt;user_id&gt;/&lt;user_secret_url_nonce&gt;

and let those people be able to edit any user data on the user model. for missing fields, we need scary red outlines and blinking things drawing people's attention to fields that need filling in

**Comment by aaronlifshin** [comment]
Don't display details about the pledge.  Thank you for pledging, here is the add'l info we need. That is all.

**Comment by hjfreyer** [comment]
I was thinking we should include the total, to assuage worries about any potential double-charge. Have it be read-only, and give an email address for any questions/issues.

**Comment by aaronlifshin** [comment]
You and JT are both feeling we should include it.  I guess if you really want to have a receipt there, that's cool.  This morning I found out that we only need to send these emails to people who donated over $200.  So, we are not creating a user accounts/management system here, just a quick page to capture some missing data.  

But, for completeness, a pledge receipt may come in handy in the future, so either way is cool with me.

**Comment by hjfreyer** [comment]
Yeah, we know everything's good, but it's good to reassure the donors
explicitly.

**Comment by brad** [comment]
@aaronlifshin Can we call this done, or do we need the pledge info?

**Comment by jtolio** [comment]
yeah let's call this done and open a new ticket if we need more info
