### ISSUE TITLE
Need an endpoint for counting the number of pledges

### ISSUE THREAD

**Issue by aaronlifshin** [MayOneUS/pledgeservice#91]
But it can't count all the pledges every time, needs to have a backend processor that writes to a field.

**Comment by brad** [comment]
Could we just add that information to the total handler?

**Comment by aaronlifshin** [comment]
Totally.

If we can do that without breaking any clients.

The harder part is the backend process that counts.

A

**Comment by brad** [comment]
Yeah, I think we can probably just piggy pack on the sharding stuff we do for the total.

**Comment by jtolio** [comment]
You don't need a backend service continuously running. Just increase the pledge model version. For that version and newer, make sure to add new pledges to a total counter. Then, once and only once, run a query and find the number of pledges with older model versions and add that to the total.

**Comment by aaronlifshin** [comment]
What about datastore contention on that counter?

**Comment by jtolio** [comment]
oh sure, right, you still need the counter sharding.

**Comment by erinzm** [comment]
I believe this is done @jwhite66?

**Comment by jwhite66** [comment]
Yes, this was finished a long time ago.
